[package]
name = "sega_cmp"
version = "0.1.0"
authors = [
    "Misty De Meo <mistydemeo@gmail.com>",
    "MrConan1",
]
license = "LGPL-3.0-only"
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2.36"
